image: maven:3.6.1

pipelines:
  default:
    - step:
        name: "Lint code and run test suite"
        caches:
          - maven
        script:
          - mvn -B verify # -B batch mode makes Maven less verbose